{% set name = "itallic" %}
{% set version = "0.0.8" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/itallic-{{ version }}.tar.gz
  sha256: b9779e9f7e5b604397f569dbf311f6eab15e44198fbc3aa41420dec4ab2176b8

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6,<4.0
  run:
    - country_converter
    - folium
    - geocoder
    - geopandas
    - geopy
    - psycopg2
    - python >=3.6,<4.0
    - scikit-learn
    - sridentify
    - xlrd

test:
  imports:
    - itallic
    - itallic.CleaningUtils
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/getiria-onsongo/itallic
  summary: Detects potential corrupt entries in a dataframe with lat,lng and country tagged data.
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - getiria-onsongo
